# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- 3.2
- 3.3
- 3.4
- 3.5
- release
- devel

matrix:
  include:
    - os: osx
      r: release

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

env:
  global:
  - NOT_CRAN="true"
  - _R_CHECK_SYSTEM_CLOCK_="FALSE"
